backend:
  name: github
  repo: hulinguistics/huling
  branch: dev
  base_url: https://133-theme.huling-dxj.pages.dev
  auth_endpoint: /api/auth

publish_mode: editorial_workflow

media_folder: "docs/.vitepress/public/upload"
public_folder: "/upload"

site_url: https://huling.org

locale: ja

collections:
  - name: "docs"
    label: "一般記事"
    folder: "src/docs"
    create: true
    slug: "{{fields.slug}}/index"

    fields:
      - label: "タイトル"
        name: "title"
        widget: "string"

      - label: "カテゴリ"
        name: "category"
        widget: "select"
        options:
          - { label: "言語学の概説", value: "linguistics" }
          - { label: "言語ごとの概説", value: "grammar" }
          - { label: "言語の比較", value: "comparison" }
          - { label: "便利機能", value: "tools" }
          - { label: "その他の記事", value: "article" }
        default: "article"

      - label: "タグ"
        name: "tags"
        widget: "list"

      - label: "パス(ラテン文字3~6文字, 「言語ごとの概説」なら言語コード)"
        name: "slug"
        widget: "string"

      - label: "コメント機能"
        name: "comment"
        widget: "boolean"
        default: "true"

      - label: "本文"
        name: "body"
        widget: "markdown"

  - name: "olympiad"
    label: "オリンピック問題解説"
    folder: "src/olympiad"
    create: true
    slug: "{{fields.olympiad}}/{{fields.year}}/{{fields.round}}/{{fields.number}}/index"

    fields:
      - label: "タイトル"
        name: "title"
        widget: "string"

      - label: "カテゴリ"
        name: "category"
        widget: "select"
        options:
          - { label: "オリンピック問題解説", value: "explanation" }
        default: "explanation"

      - label: "大会情報"
        name: "olympiad_info"
        widget: "object"
        fields:
          - {label: "大会名略称(ラテン小文字)", name: "name", widget: "string"}
          - {label: "大会開催年", name: "year", widget: "number"}
          - {label: "大会ラウンド", name: "round", widget: "number", required: false}
          - {label: "大問番号", name: "number", widget: "number"}

      - label: "タグ"
        name: "tags"
        widget: "list"

      - label: "コメント機能"
        name: "comment"
        widget: "boolean"
        default: "true"

      - label: "本文"
        name: "body"
        widget: "markdown"
