backend:
  name: github
  repo: hulinguistics/huling
  branch: dev
  base_url: https://huling.org
  auth_endpoint: /api/auth

publish_mode: editorial_workflow

media_folder: "docs/.vitepress/public/upload"
public_folder: "/upload"

site_url: https://huling.org

locale: ja

collections:
  - name: "docs"
    label: "語学・言語学の記事"
    folder: "src/docs"
    create: true
    slug: "{{fields.slug}}"

    fields:
      - label: "タイトル"
        name: "title"
        widget: "string"
        hint: |
          言語ごとの概説なら「ドイツ語 / Deutsch」など

      - label: "カテゴリ"
        name: "category"
        widget: "select"
        options:
          - { label: "言語学の概説", value: "linguistics" }
          - { label: "言語ごとの概説", value: "grammar" }
          - { label: "言語の比較", value: "comparison" }
          - { label: "便利機能", value: "tools" }
          - { label: "その他の記事", value: "article" }

      - label: "タグ"
        name: "tags"
        widget: "list"
        hint: |
          [タグ一覧](https://huling.org/tags/)

      - label: "パス"
        name: "slug"
        widget: "string"
        hint: |
          ラテン小文字, 算用数字, 半角ハイフン, 3字以上.
          言語ごとの概説なら3文字の言語コード (**deu**, **fra** など.
          [ISO 639-2](https://www.loc.gov/standards/iso639-2/php/code_list.php),
          [ISO 639-3](https://iso639-3.sil.org/code_tables/639/data)
          参照)
        pattern: ['[a-z0-9-]{3,}', 'ラテン小文字, 算用数字, 半角ハイフン, 3字以上']

      - label: "コメント機能"
        name: "comment"
        widget: "boolean"
        default: "true"

      - label: "本文"
        name: "body"
        widget: "markdown"
