backend:
  name: github
  repo: hulinguistics/huling
  branch: dev
  base_url: https://huling.org
  auth_endpoint: /api/auth

publish_mode: editorial_workflow

media_folder: src/public/upload
public_folder: /upload

site_url: https://huling.org

locale: ja

collections:
  - name: docs
    label: 語学・言語学の記事
    folder: src/docs
    create: true
    slug: "{{fields.id}}"
    preview_path: "docs/{{slug}}"
    preview_path_date_field: published_at

    fields:
      - label: タイトル
        name: title
        widget: string
        hint: |
          言語ごとの概説なら「ドイツ語 / Deutsch」など

      - label: 記事ID
        name: id
        widget: string
        hint: |
          ラテン文字, 算用数字, 半角ハイフン, 3字以上.
          ダイアクリティカルマーク付きラテン文字不可.
          言語ごとの概説なら3文字の言語コード (**deu**, **fra** など.
          [ISO 639-2](https://www.loc.gov/standards/iso639-2/php/code_list.php),
          [ISO 639-3](https://iso639-3.sil.org/code_tables/639/data)
          参照).
          記事のURLは「https://huling.org/docs/(id)」.
        pattern: ['[a-zA-Z0-9-]{3,}', 'ラテン文字, 算用数字, 半角ハイフン, 3字以上']

      - label: カテゴリ
        name: category
        widget: select
        options:
          - { label: 言語学の概説, value: linguistics }
          - { label: 言語ごとの概説, value: grammar }
          - { label: 便利機能, value: tools }
          - { label: その他の記事, value: article }

      - label: タグ
        name: tags
        widget: list
        hint: |
          [タグ一覧](https://huling.org/tags).
          「#」不要.
          仕切り文字は半角コンマ「,」.

      - label: コメント機能
        name: comment
        widget: boolean
        default: true

      - label: 本文
        name: body
        widget: markdown

  - name: olympiad
    label: オリンピック関連の記事
    folder: src/olympiad
    create: true
    slug: "{{fields.id}}"

    fields:
      - label: タイトル
        name: title
        widget: string
        hint: |
          問題解説なら「JOL2017-3 モンゴル語」など

      - label: 記事ID
        name: id
        widget: string
        hint: |
          ラテン文字, 算用数字, 半角ハイフン, 3字以上.
          ダイアクリティカルマーク付きラテン文字不可.
          問題解説なら「(大会略称)(開催年)(ラウンド)-(問題番号)」.
          例) 「JOL2017-3」「UKLO2021R1-1」など.
          記事のURLは「https://huling.org/olympiad/(id)」.
        pattern: ['[a-zA-Z0-9-]{3,}', 'ラテン文字, 算用数字, 半角ハイフン, 3字以上']

      - label: カテゴリ
        name: category
        widget: select
        options:
          - { label: 言語学オリンピックについて, value: general }
          - { label: オリンピック問題解説集, value: explanation }

      - label: タグ
        name: tags
        widget: list
        hint: |
          [タグ一覧](https://huling.org/tags).
          「#」不要.
          仕切り文字は半角コンマ「,」.

      - label: コメント機能
        name: comment
        widget: boolean
        default: true

      - label: 本文
        name: body
        widget: markdown
